version: '3.4'

services:
  mongo:
    image: mongo:6.0.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq

  redis:
    image: redis:7.0.8-alpine
    ports:
      - "6379:6379"

  app.services.gateway:
    image: ${DOCKER_REGISTRY-}appservicesgateway
    build:
      context: .
      dockerfile: App.Services.Gateway/Dockerfile

  app.services.users:
    image: ${DOCKER_REGISTRY-}appservicesusers
    build:
      context: .
      dockerfile: App.Services.Users/App.Services.Users/Dockerfile

  app.services.departments:
    image: ${DOCKER_REGISTRY-}appservicesdepartments
    build:
      context: .
      dockerfile: App.Services.Departments/App.Services.Departments/Dockerfile



  app.services.organizations:
    image: ${DOCKER_REGISTRY-}appservicesorganizations
    build:
      context: .
      dockerfile: App.Services.Organizations/App.Services.Organizations/Dockerfile

  app.services.teams:
    image: ${DOCKER_REGISTRY-}appservicesteams
    build:
      context: .
      dockerfile: App.Services.Teams/App.Services.Teams/Dockerfile


  app.services.games:
    image: ${DOCKER_REGISTRY-}appservicesgames
    build:
      context: .
      dockerfile: App.Services.Games/App.Services.Games/Dockerfile

